language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    - secure: DD3PDEk62XEanjqB8rPV+fTFh3MZXS55jBpNiIudCx1fu0gqJdLlU5OtuEiiHMh3qPpaa3tudDCQh5/7oItRdTXYwUs9UCT+8LtQrbEODo7zPWWdRS9Qn0PL10D+ncMuLDZeEJjNpx4/RFbaX56ThZBJ/QHkhZ7n3/YZYAVH4I84tshkoolJtHHIGZTmmNJFRMKI1BHRSEowWCMunS9B2xONVRrLWQm4nK2HMw7g7rgNhHMZ5uhlKBLuyBGIvRNMqRjYp/pyXh5tmd06zu2ASXRAcydDvfZSlhOZPwo6cZ+MX9/U5+sGAYzkBGYkBloXiAPY1CAZObYwQn/MKodMg6++3oq07deNz0qsuRqciEsKjPZ+AXQuBso1g5xojmUVoUwNjF6szSvcDN9N2rrUadXvbymDM6tIV6KrW88FYzHQm03KiYYC4lzgdbgixVOdqZY7MKZSdWpwMHMGH2nxZK5NDdnhqoU+do8SxrFz9o8XAsbrwWdCusuUGT4mHqV0NnAN/zPYFXWrLBtmflZChJ5lAgYhgMGhl13fo9ca79xDdFu3hvaZHY5Y7AIlZGOWsnH2rxKZAQXM+YX8hq4RvtZPT+KIbhZdQs3je75P8PRS6HeU5GvUxhnrVtkrkM5SYF5bzKNKPxCIV8HspfiDjpCy1XseytQxvPnTcPMHJew=
env:
  global:
    - secure: K46saRKxFruRDv6LyTRkdr4UaiX3ma4OC7RFp/BSw+Sr3Pk105hzd8Be5cMxBE9sjWvcrxB1JvwkY7W+iWSxQtC+xzQAPxON+34vUBwS319Zqxnc5HsB/6X6jRNnuSdg+CFg4NMpBXPQAUFHJT2SeTNvgL2G7RdiuAOal9/EG+dcKgpfugawWGpAnG/k9VAP4u3QLUjFNTKvDMwpaX0yGOJVPoOPOk+09Fvy157cotG3j5O33iAxMNb2rQepFNsQiQ6XwuoDFJyBKJsQ4tvRcmRxlW7D4efSn/TjibOtM2NcEbbB2XMGPhi9Q8b8e94ZnKrRvMPa1n3KHu1PyhiC8H2dg29+dOmtJLGGLChcKhkON3J4dJEKrFMDLXEHkwY2rS7X4Wda83w7DdIIIegOQ/mvhYRHaPzVeDA/+vklLpGlWyEohOJy61OZv5e3xaO+HdCMGY6nqvcVrDkj+6Bvr/NwM608Ynp6NNTQXuW2iARSW2nz+rKIgaG5ThNBOX3+KmVrjvQpZv3jP4uMV5MLjWQk7KYS6TYWULUI29LCNiUE8lgl19BqFnGJ7yXPZaWLGBjDagVQtymGq3wdKs1x7cHN4dNQD8LdkpQnlvsGJtX7jT3Mx+S+6tyCRiLztvmESt454drP7O+GI5S2OCARcT4YHUw0ascdirqp5oJ9EV8=
    - secure: VU4EGU8KpLgZ7IFc35ZnuxZTRnNwUggxoeQuOU9G+HLc/s1FLgKsyAcEvN6tw3BTT4ZjZn3n6CB+qvDWWs5sBrp11Ty30Zp0CAFY3qzgQ+yBYLeI07YVnOGW1NwHIkDG6jgRUQ3krKkdwAiDz1+Zr80TKnmxi12g85stbhdaMypl/1kqmt9T7rztXxHfvETIGJsAD+SHTQxpZeu9brxGMAgTdBFn2BJYLRZWZNCO/oLqYdnD/R8yFbLJ6esFEq70Jtdpr7BYq+6f1me5J2OnyObPd/VgAjuMFyrxok2h1SXheHIfUVuhXRK1HZnqRVryv1ZCjMYFzHa5RoCPJFjUe/Hd4tx01RrzqaLRbAjVKk5yaDrk8LGwozx38uYx9pIcmxqI4aq46ZI6zKtvTAtda60f9HY1rxsMZeLA0ea5NW8GFnOE4Waqx61Nm/egnjz7kDmjYcEBgHYqnX2e0MC6a7oWdYef4br6hodQbRhHLEKNMKnMiQF2apzw5ydpNZuAjunuVtjsAOoQwm/6G4FJg97sMa6jip7v1vQktxrMaWCtdNe8rZQvPSYrDOSllhSU926Dk89sh6tUffVCLHBJChGp6dpef4q+VALTVcRcJF4XKI8kDJFIrUX8hox7Sh0CEO4UHazJ3tdVvjA3yS1b2EzipBR58qy7wcB/M9pfdDc=
