language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
env:
  global:
    - secure: VFtLccSSIxYSD+ytTKZkQnULQczS53DQLu/71Hs/haGtle1BXqK7rkJY9OXXujfOWmRoHi7vmvHv475aqNBYlboigUA2s16GV5ZqxD43V+tDIYQGYWueyf95a0uDkmVKelWBuIx0sH987SUmLgloWVVvnNH4VPTlyDvqIjueWFWS+PWb2zqf31ZbUEmRhY7tK9g6bNMVlzMIrlTwGjYlsGPnGWpPe9Z1L0gsqbb+PlgyUs/FVzOn296p0SMtBwGNpySr4AwRn1AJhpw8AtzQVCSCQRsWyTlRLJltZfrgL9Mr8peQPltXVJTCuBJiwGX55luJYpTIAac1rF7AMBe5M1H+d3GFr4SO+POYn9+vPbq88oTUckS7mevinlSUtVQiHNPJHcd8myrjOaSjmEP4SB63XFLj0eHNk5iVY9D6oIg7spiWvGdbAkvJlt3rM3bWyrVt9of7PDjytfdr8kAVg/tws+NSnBE9VDUqfjLc93Zz5RTuibDAJSPcWvSJtst+jvtezQfgXf7oCDPvI8ILgHQ7Loj+aDKJZzFd55gFWjG3GvcnwBylliuUmpDc7qMQbFAcq0pC5gcx+Gq7fm3UbzcMqW4A5BHy/PS1zMt7iRwXzfR5WUpKn69sGUwOQP8ZdLcMvndUFGuJCYsuM5OsaaDsIM6wNkrsVC+cqfof7Bk=
    - secure: bRGZmhVEm4R/DzkeiU2NVLXtP8aqYISjFivgcYmZ7v48c3VhJrdS1lCJnMK8uTcJ+tCZ8rblQQAqoyj/H96pY0duSSN4tc32wSWod/JjZQ6w84k4EBpYXHkz8UblYY/TsXEn0PQHVjjl3/VAN1AIfzkjHzGDJb5QvrA6Y+aWaZJxJ9w6e+GPQ6nxtnt07g0nHDcT4R8y0fimzvTLgb6q7RMMW/3lioI+21fiRHzvApSXeHrce+m+IuUHhHHDOSN1a1sDcKBniBProGE8gP/x6PN8Bjz0T5URwgrXRV2Mr438FbOCFl5Al+q+W+ai9BBR2tifo3+78pEfQn7zgZZdEvaL40ShKRYPr+5HtgXIqYdye+B5D0kFTijENvwfcHadRJZTWafPTyHYVFPdeKBWCyu9TonH3cgvtEiuxXuLxvsBnWB4WnMnuREDTZYExyFx9MWanisAghmLq6NCIw1NKXyXCmziSO5+raBXdlj12tgNJ+tYXBDMYZPY7RuegL1AudwQrGusf6o1cAL37ZEaL0KGPNdhyuthvilJtDgGBbU/VqqoR0aP9O+hO2hSinU56aSqehITSBUFtBw7q4SY6r8WC98usoCWiv4EwLBQATZwfGAZy9D+oAOeJjn8UkDZ++9uaMeZxpyOotTkar2nIeFFeudqjn6NuI4u4eo8ZJM=
